#server.port=80
##spring.main.banner-mode=
##spring.banner.image.location=123.jpeg
##logging.level.root=info
#country:China
##???????
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qwerty85910859
    url: jdbc:mysql://localhost:3306/ssm_db