CREATE TABLE dept(
deptno MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
dname VARCHAR(20) NOT NULL DEFAULT " ",
loc VARCHAR(13)NOT NULL DEFAULT " ");
INSERT INTO dept VALUES (10,'ACCOUNTING','NEW YORK'),(20,'RESEARCH','DEALLAS'),(39,'SALES','CHICAGO'),(40,'OPERATIONS','BOSTON');

SELECT *FROM dept;

-- 员工表
