#修改表的操作练习 
ALTER TABLE emp
ADD image VARCHAR(32)NOT NULL DEFAULT ''
AFTER RESUME
 DESC employee
ALTER TABLE employee
MODIFY job VARCHAR(60) NOT NULL DEFAULT ''

ALTER TABLE emp
DROP sex
RENAME TABLE emp TO employee

ALTER TABLE employee CHANGE `NAME` user_name VARCHAR(32) NOT NULL DEFAULT '' 